# Generated by Django 5.2.6 on 2025-09-12 16:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the regional council.', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FreshwaterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text="Geographic coordinates (Point) of the plan's location.", srid=4326)),
                ('map_image', models.ImageField(blank=True, help_text='Generated map image for the plan.', null=True, upload_to='map_images/')),
                ('council', models.CharField(help_text='The council associated with the plan.', max_length=255)),
                ('generated_plan', models.TextField(help_text='The generated content of the freshwater plan.')),
                ('pdf_preview', models.FileField(blank=True, help_text='A PDF preview of the generated plan.', null=True, upload_to='previews/')),
                ('pdf_final', models.FileField(blank=True, help_text='The final PDF of the generated plan.', null=True, upload_to='finals/')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', help_text='The payment status of the plan.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshwater_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
