# Generated by Django 5.2.6 on 2025-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='activity_features',
            field=models.JSONField(blank=True, help_text='User-drawn activity features (GeoJSON).', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', help_text='Status of admin details pre-population/generation pipeline.', max_length=20),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='vulnerability_features',
            field=models.JSONField(blank=True, help_text='User-drawn vulnerability features (GeoJSON).', null=True),
        ),
    ]
