# Generated by Django 5.2.6 on 2025-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0002_freshwaterplan_activity_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='farm_address',
            field=models.TextField(blank=True, help_text='Physical address of the farm.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='land_use',
            field=models.CharField(blank=True, help_text='Primary land use of the farm.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='leased_area_ha',
            field=models.FloatField(blank=True, help_text='Leased or licensed area in hectares.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='legal_land_titles',
            field=models.TextField(blank=True, help_text='Legal land titles and parcels.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='operator_contact_details',
            field=models.TextField(blank=True, help_text='Contact details for the operator.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='operator_name',
            field=models.CharField(blank=True, help_text='Name of the farm operator.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='operator_nzbn',
            field=models.CharField(blank=True, help_text='New Zealand Business Number (if applicable).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='owner_contact_details',
            field=models.TextField(blank=True, help_text='Contact details for the owner.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Name of the land owner, if different.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='plan_preparer_name',
            field=models.CharField(blank=True, help_text='Name of the person who prepared the plan.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='resource_consents',
            field=models.TextField(blank=True, help_text='Current relevant resource consents.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='total_farm_area_ha',
            field=models.FloatField(blank=True, help_text='Total farm area in hectares.', null=True),
        ),
    ]
