# Generated by Django 5.2.6 on 2025-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0003_freshwaterplan_farm_address_freshwaterplan_land_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshwaterplan',
            name='council',
            field=models.CharField(blank=True, help_text='The council associated with the plan.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freshwaterplan',
            name='generated_plan',
            field=models.TextField(blank=True, help_text='The generated content of the freshwater plan.', null=True),
        ),
    ]
