# Generated by Django 5.2.6 on 2025-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0004_alter_freshwaterplan_council_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshwaterplan',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Status of admin details pre-population/generation pipeline.', max_length=20),
        ),
    ]
