# Generated by Django 5.2.6 on 2025-09-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0005_alter_freshwaterplan_generation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='generation_progress',
            field=models.JSONField(blank=True, default=list, help_text='A log of steps taken during the generation process.'),
        ),
        migrations.AlterField(
            model_name='freshwaterplan',
            name='generation_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', help_text='Status of admin details pre-population/generation pipeline.', max_length=20),
        ),
    ]
