# Generated by Django 5.2.6 on 2025-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0006_freshwaterplan_generation_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='council_authority_name',
            field=models.CharField(blank=True, help_text='The official council name as identified by the RAG model.', max_length=255, null=True),
        ),
    ]
