# Generated by Django 4.2.24 on 2025-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0007_freshwaterplan_council_authority_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='catchment_area_info',
            field=models.JSONField(blank=True, help_text='Aggregated catchment data from ArcGIS.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='degradation_summary',
            field=models.TextField(blank=True, help_text='Human-readable summary of degradation status.', null=True),
        ),
    ]
