# Generated by Django 4.2.24 on 2025-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0008_freshwaterplan_catchment_area_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshwaterplan',
            name='degradation_summary',
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='catchment_name',
            field=models.CharField(blank=True, help_text='The name of the REC catchment the property is located in.', max_length=255, null=True),
        ),
    ]
