# Generated by Django 4.2.24 on 2025-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0009_remove_freshwaterplan_degradation_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='slope_class',
            field=models.CharField(blank=True, help_text='Dominant slope class from regional data (e.g., LiDAR).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Dominant soil type from regional data (e.g., Topoclimate).', max_length=255, null=True),
        ),
    ]
