# Generated by Django 4.2.24 on 2025-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0010_freshwaterplan_slope_class_freshwaterplan_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='arcgis_slope_angle',
            field=models.FloatField(blank=True, help_text='Slope angle in degrees from ArcGIS data.', null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='erodibility',
            field=models.CharField(blank=True, help_text='Erodibility classification from ArcGIS data.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='nutrient_leaching_vulnerability',
            field=models.CharField(blank=True, help_text='Nutrient leaching vulnerability from ArcGIS data.', max_length=100, null=True),
        ),
    ]
