# Generated by Django 4.2.24 on 2025-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0011_freshwaterplan_arcgis_slope_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='parcel_features',
            field=models.JSONField(blank=True, help_text='Features from Koordinates parcel layer 53682.', null=True),
        ),
    ]
