# Generated by Django 4.2.24 on 2025-09-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0012_freshwaterplan_parcel_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshwaterplan',
            name='land_use',
        ),
        migrations.RemoveField(
            model_name='freshwaterplan',
            name='parcel_features',
        ),
    ]
