# Generated by Django 4.2.24 on 2025-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0013_remove_freshwaterplan_land_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='map_snapshot',
            field=models.TextField(blank=True, help_text='Base64 encoded PNG of the map snapshot.', null=True),
        ),
    ]
