# Generated by Django 4.2.24 on 2025-09-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0014_freshwaterplan_map_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshwaterplan',
            name='map_snapshot',
            field=models.ImageField(blank=True, help_text='Snapshot of the map for the activities step.', null=True, upload_to='plan_snapshots/'),
        ),
    ]
