# Generated by Django 4.2.24 on 2025-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0015_alter_freshwaterplan_map_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='risk_management_data',
            field=models.JSONField(blank=True, help_text='Data from the risk management table (Step 5).', null=True),
        ),
    ]
