# Generated by Django 4.2.24 on 2025-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0016_freshwaterplan_risk_management_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshwaterplan',
            name='risk_management_data',
        ),
        migrations.AddField(
            model_name='freshwaterplan',
            name='physical_works_features',
            field=models.JSONField(blank=True, help_text='GeoJSON features for physical works.', null=True),
        ),
    ]
