# Generated by Django 4.2.24 on 2025-10-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0017_remove_freshwaterplan_risk_management_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='risk_management_data',
            field=models.JSONField(blank=True, help_text='Data for the risk management table.', null=True),
        ),
    ]
