# Generated by Django 4.2.24 on 2025-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0018_freshwaterplan_risk_management_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterplan',
            name='soil_drainage_class',
            field=models.CharField(blank=True, help_text='Soil drainage classification from FSL data.', max_length=100, null=True),
        ),
    ]
