# Generated by Django 4.2.24 on 2025-10-06 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_generator', '0020_freshwaterplan_vulnerability_analysis_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='The name of the monitoring site.', max_length=255)),
                ('hilltop_site_id', models.CharField(help_text='The unique identifier for the site in the Hilltop API.', max_length=255, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates (Point) of the monitoring site.', srid=4326)),
            ],
        ),
    ]
